### ISSUE TITLE
Livewire v3

### ISSUE THREAD

**Issue by wverhoogt** [enflow/livewire-twig#13]
Hi,
Now that Livewire v3 is available (albeit in beta) this package could be update to support it. I´ve already looked at it, an it looks doable, though definitely some work.
Because Livewire is still in beta, this package would also remain in beta, I guess. 
Out of curiosity: I´m wondering if you still use this extension in your company.

**Comment by mbardelmeijer** [comment]
Hi there! For sure, we use this package often for Enflow projects. I haven't dived into Livewire 3, but it's something that we want to support for sure.

My preference would have an `enflow/livewire-twig` package that supports both Livewire 2 & Livewire 3. If that's not doable, we can release a new major version with Livewire 3 support.

PRs to support Livewire 3 are welcome :)

**Comment by wverhoogt** [comment]
I´ve already coded a bit, and a version which support both v2 and v3 would require conditional code in the twig compiler part because v3 uses a different way of supporting child components. Possible, but more work and more difficult to test.
I use this package as a basis for a WinterCMS plugin which aims to support Livewire in that environment. Apparently, your TowerCMS also uses Laravel and Twig?

**Comment by wverhoogt** [comment]
I´ve already coded a bit, and a version which support both v2 and v3 would require conditional code in the twig compiler part because v3 uses a different way of supporting child components. Possible, but more work and more difficult to test.
I use this package as a basis for a WinterCMS plugin which aims to support Livewire in that environment. Apparently, your TowerCMS also uses Laravel and Twig?

**Comment by mbardelmeijer** [comment]
Check. Then having a new major version that only supports Livewire 3 would work. We might backport support for other Laravel/PHP versions to the other major version in the future if we need it.

We can use this package in our CMS, although it's mostly used in custom Laravel applications. We build all Laravel applications with Twig, so this package was a must for us to be able to use Livewire.

If you would like to make a PR, happy to review it!

**Comment by mbardelmeijer** [comment]
Fixed with https://github.com/enflow/livewire-twig/pull/16
