### ISSUE TITLE
Proposition : use STRING_TYPE instead of NAME_TYPE

### ISSUE THREAD

**Issue by kblais** [enflow/livewire-twig#3]
Hi,

What would you think about using `STRING_TYPE` instead of the `NAME_TYPE` in `LivewireTokenParser::parse()` ?
This would allow calling components placed in a folder, like Livewire allows you to do (using the dot notation).

This would be a breaking change though, because the current notation would not work anymore. Maybe it is possible to allow both `STRING_TYPE` and `NAME_TYPE`, but I'm not sure how...

**Comment by mbardelmeijer** [comment]
Hey @kblais, thanks for your proposal. Can you provide an example of an use-case that would open up? And what current cases would be broken by changing the type?

Cheers!

**Comment by kblais** [comment]
Well, imagine you have a component like `\App\Http\LiveWire\Table\TextSearchField`.

In Blade Livewire, you can call it using `<livewire:table.text-search-field>` (or, but i'm not sure, with the shortcut `@livewire('table.text-search-field')`).

With Twig Livewire, you can't call this component using `{% livewire table.text-search-field %}`, because Twig will throw an ErrorException `Unexpected token "punctuation" of value "." ("end of statement block" expected).`.

You can't either use `{% livewire 'table.text-search-field' %}`, because it will throw a new ErrorException `Unexpected token "string" of value "tables.userTable" ("name" expected).`.

Using `STRING_TYPE` instead of the `NAME_TYPE` would force developpers to put `'` around the name of the component, like this : `{% livewire 'component-name' %}`. I've been (quickly) searching if there was an easy way to expect either `NAME_TYPE` or `STRING_TYPE`, but couldn't find it...

**Comment by mbardelmeijer** [comment]
Thanks for the explanation, that makes sense and i think it's a good idea to move to the `STRING_TYPE` in the future. As it's a breaking change, we can only make this for the v2 release. I'll keep this issue open for now and revisit it for a future release so that we may can combine multiple breaking changes.

PR's to change this with tests are welcome!

**Comment by mbardelmeijer** [comment]
Supported added with #4
